FROM nginx:1.14.2

# Expose port 80 (same as containerPort in the YAML)
EXPOSE 80

# You can add any additional configuration or setup here if needed
# For example, copying custom files or configuring NGINX settings

# Start NGINX when the container runs
CMD ["nginx", "-g", "daemon off;"]
